name: Checks
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 17.x
          - 18.x
    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pre-requisites
        run: npm install -g yarn

      - name: Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
